// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARw3AJ75i4oHsTbLSA4OSi1_es1UyI0Z0',
    appId: '1:740423052334:web:e287aa0424eb91151f03bf',
    messagingSenderId: '740423052334',
    projectId: 'healthai-d2aea',
    authDomain: 'healthai-d2aea.firebaseapp.com',
    storageBucket: 'healthai-d2aea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCttQv-GCsPKXVezmaTQl9KKwJtAk016VQ',
    appId: '1:740423052334:android:a736fa7991ea0f5a1f03bf',
    messagingSenderId: '740423052334',
    projectId: 'healthai-d2aea',
    storageBucket: 'healthai-d2aea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfN1wP-xv9Y8POz4F3-M9xlVwaSkRago0',
    appId: '1:740423052334:ios:f44af7316f732e651f03bf',
    messagingSenderId: '740423052334',
    projectId: 'healthai-d2aea',
    storageBucket: 'healthai-d2aea.firebasestorage.app',
    iosBundleId: 'com.example.medilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfN1wP-xv9Y8POz4F3-M9xlVwaSkRago0',
    appId: '1:740423052334:ios:f44af7316f732e651f03bf',
    messagingSenderId: '740423052334',
    projectId: 'healthai-d2aea',
    storageBucket: 'healthai-d2aea.firebasestorage.app',
    iosBundleId: 'com.example.medilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARw3AJ75i4oHsTbLSA4OSi1_es1UyI0Z0',
    appId: '1:740423052334:web:f26d43ced9bdeca81f03bf',
    messagingSenderId: '740423052334',
    projectId: 'healthai-d2aea',
    authDomain: 'healthai-d2aea.firebaseapp.com',
    storageBucket: 'healthai-d2aea.firebasestorage.app',
  );
}
